### ISSUE TITLE
Call Your Brother 미션 번역 오류 제보

### ISSUE THREAD

**Issue by AfxousaAjagara** [GoLani11/SPT-Korean-Project#3]
[예시](https://gall.dcinside.com/mini/sptarkov/26260)
타르코프 갤러리에도 올라온 이슈입니다.
Call Your Brother 의 과제 이름과 목표가 거꾸로 올라와 있습니다.
또한 팩토리 보스 이름이 타길라에서 킬라로 오역되었습니다.

**Comment by GoLani11** [comment]
현재 수정 완료했고 오늘 부로 버전 업데이트되면 수정되서 출력될겁니다. 제보 감사합니다!
