### ISSUE TITLE
전술 손전등 오역

### ISSUE THREAD

**Issue by denbeu** [GoLani11/SPT-Korean-Project#4]
제보할 텍스트 : Oilght Baldr Pro 전술 손정등&레이저 지시기

내용 설명 : 전술 손정등이 아닌 전술 손전등으로 표시해야합니다.

수정 예상 내용 : Oilght Baldr Pro 전술 손전등&레이저 지시기

**Comment by GoLani11** [comment]
오타 부분 확인해서 다음 업데이트때 반영하겠습니다. 감사합니다!
